<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Codefarts.BuildHelper.PowerShell</AssemblyName>
    <LangVersion>default</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>1.0.0.0</Version>
    <Title>Powershell command for buildhelper</Title>
    <Authors>Dean Lunz</Authors>
    <Copyright>Codefarts</Copyright>
    <Company>Codefarts</Company>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <RepositoryType>C#</RepositoryType>
    <PackageProjectUrl>https://github.com/createdbyx/Codefarts.BuildHelper.git</PackageProjectUrl>
    <RepositoryUrl>https://github.com/createdbyx/Codefarts.BuildHelper.git</RepositoryUrl>

    <IncludeSymbols>true</IncludeSymbols>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Codefarts.BuildHelperLib" Version="2024.6.4.3" />
    <PackageReference Include="Codefarts.DependencyInjection.CodefartsIoc" Version="2023.5.25.12" />
    <PackageReference Include="PowerShellStandard.Library" Version="5.1.0-preview-06">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
