<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyVersion>2021.1.25.0</AssemblyVersion>
    <FileVersion>2021.1.25.0</FileVersion>
    <AssemblyName>BuildHelper</AssemblyName>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Options.cs" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="..\stylecop.json" Link="stylecop.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Codefarts.DependenceyInjection" Version="2023.1.30.5" />
    <PackageReference Include="Codefarts.IoC" Version="2023.2.12.222" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Reflection.MetadataLoadContext" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="config.xml" />
    <Content Include="config.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Codefarts.BuildHelper.ConsoleReporter\Codefarts.BuildHelper.ConsoleReporter.csproj" />
    <ProjectReference Include="..\Codefarts.BuildHelper.XMLFileConfigManager\Codefarts.BuildHelper.XMLFileConfigManager.csproj" />
    <ProjectReference Include="..\Importers\Codefarts.BuildHelper.XmlCommandFileReader\Codefarts.BuildHelper.XmlCommandFileReader.csproj" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="powershell.exe -ExecutionPolicy Unrestricted -noprofile -nologo -noninteractive -Command .'$(ProjectDir)deploy.ps1'" />
  </Target>
</Project>