<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Codefarts.DependencyInjection" Version="2023.5.25.1" />
        <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="..\..\stylecop.json">
            <Link>stylecop.json</Link>
        </AdditionalFiles>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Codefarts.BuildHelperLib\Codefarts.BuildHelperLib.csproj" />
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <Exec Command="powershell -File &quot;$(SolutionDir)CopyPlugin.ps1&quot; -vs_SolutionDir &quot;'$(SolutionDir)'&quot; -vs_ConfigurationName &quot;'$(ConfigurationName)'&quot; -vs_TargetFramework &quot;'$(TargetFramework)'&quot; -vs_ProjectName &quot;'$(ProjectName)'&quot; -vs_ProjectDir &quot;'$(ProjectDir)'&quot; -vs_OutDir &quot;'$(OutDir)'&quot;" />
    </Target>
</Project>
